# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        # cache: 'npm'

    - name: npm install
      run: npm i

    - name: make test-coverage
      run: make test-coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
